### PR TITLE
Move "types" into the package

### LINKED ISSUE #39: Typescript typings are not found
Inspired by the SymfonyCasts series on Stimulus, I've started using it in my project. However, I'ld like to use Typescript. I can't get the `@symfony/stimulus-bridge-types` package to work. Since it's not in the @types -namespace, it's not automatically detected. Therefore I've adapted my typeRoots-property in tsconfig.json, but it's still not detected:
```{
  "compilerOptions": {
    "target": "esnext",
    "module": "commonjs",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "typeRoots": [
      "node_modules/@types",
      "node_modules/@symfony/stimulus-bridge-types"
    ]
  }
}
```

Is there a specific reason to put the index.d.ts in a separate package? Since it's so small, I think it can be bundled in the main package (https://www.typescriptlang.org/docs/handbook/2/type-declarations.html#external-definitions)

### PR DESCRIPTION
**Pull request by weaverryan**
Fixes #39 

Instead of having a separate `@symfony/stimulus-bridge-types` package, it's easier (both for us but mostly for users) to embed it directly in the package.

Cheers!

### CODE REVIEW

**Comment by chapterjason** [comment]
Hey :)

1. The `package.json` file in the types folder can be removed and we should mark it as deprecated on npm (never had the case before)?
2. The types file can look like this if it is served with the source:

```typescript
/*
 * This file is part of the Symfony package.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

import { Application } from "stimulus";

export function startStimulusApp(context?: __WebpackModuleApi.RequireContext): Application;

```

3. As in my first proposal in #8 we will have the issue that types for `__WebpackModuleApi.RequireContext` will be missing. Adding `@types/webpack-env` as dependency will fix that.

**Comment by chapterjason** [comment]
@tgalopin I proposed that for encore some months/years ago. The drawback is that you can't test dev branches, as you need to compile first. Can't find the comment anymore. Or you need to check in the dist (what is already the case, what I would prefer to get rid of.)

**Comment by tgalopin** [comment]
Ah right, I mixed things up, this package is already TS. Let's finalize this PR then!

**Comment by weaverryan** [comment]
When I output all of the .d.ts files locally, it creates (of course ) .d.ts files or ALL of the files. Do we want to do that? Really, only the `startStimulusApp` is something the user should want the type for. WDYT?

**Comment by chapterjason** [comment]
I wouldn't maintain the types separately.

IIRC with `{ "types": "./dist/index.d.ts" }` the consumer only get types for exports defined in the given file. So it wouldn't affect the consuming tsc or ide.

image

You only get the other types if you explicit import them like that:

image

**Comment by dehy** [comment]
Any news about this issue ? Having the types inside the package would be great.

**Comment by weaverryan** [comment]
@chapterjason can you have a look now?

The only weird part is that, while you can build the types with `yarn tsc`, it will also output `.d.ts` files for files like `dist/util/get-stimulus-comment-options.d.ts`, which is not a file we actually build into the `dist/` folder. For now, I've just manually not included those extra files.

**Comment by chapterjason** [comment]
@weaverryan LGTM

In the end it's just javascript and the method is theoretically still loadable and useable. If you import `@symfony/stimulus-bridge/util/get-stimulus-comment-options` you don't have types. But I think it's fine to ignore it, cause it isn't part of the public API.

**Review by chapterjason — APPROVED** [review]

**Review by chapterjason — APPROVED** [review]

**Pull request merged**
